include /home/ben/.config/sway/config

# Headless WayVNC-specific overrides
output HEADLESS-1 resolution 1920x1080

exec --no-startup-id /home/ben/.local/bin/wayvnc-launch.sh
exec --no-startup-id kitty
